### ISSUE TITLE
FormData empty [object Object]

### ISSUE THREAD

**Issue by UnleashSpirit** [riversun/ajax-client#6]
Hi, I begin to switch an old custom javascript library in typescript.
To remove jQuery dependenciy I choose your work, but I hava 'lots' of 'issues'

First, it's not a real problem, I think you should be case independent in post / POST get / GET.
As jQuery I think, contentType and dataType should not be mandatory and have default value.

The main problem for me is that I use contentType: 'application/x-www-form-urlencoded', and the Form Data posted are empty.
```typescript
var far = 'x';
client.ajax({
      url: url,
      type: 'post',
      data: {
          foo: 'bar',
          bar: far
      },
      contentType: 'application/x-www-form-urlencoded',
      crossDomain: true,
      xhrFields: {
        withCredentials: true,
      }
})
```
![image](https://user-images.githubusercontent.com/6216968/99967173-c4343700-2d97-11eb-8179-0f65c59c3f4a.png)

Using JSON.stringify, does not work either.

Does crossDomain and xhrFields also work in your library ?

Regards.

**Comment by UnleashSpirit** [comment]
I answer myself. Using URLSearchParams seems to work
```typescript
data: new URLSearchParams({
	modeRedirect: 'true',
	xmlcontent: context.xmlcontent,
	jtd: context.compte.jtd,
})
```

Sorry for the issue

**Comment by UnleashSpirit** [comment]
I saw that you do some changes based on my remarks, I'm glad :)

I tried new version, 1.4.1, and I have some observations.
I think the content-type checking for, 'application/x-www-form-urlencoded; charset',  may not be strict but more, index of, starts-with or regex math cause it's often 'application/x-www-form-urlencoded; charset=UTF-8'

A bit more disturbing, when I bundle it, I have 'Uncaught TypeError: p is not a constructor' error at runtime from your library. By checking source, p seems to be URLSearchParams
```typescript
if("application/x-www-form-urlencoded"===t.contentType){var s=function(t){for(var e=new p,n=0,r=Object.keys(t)
```

My use of URLSearchParams was a first try workaround, may be not 'vanilla javavascript' enought

Regards

**Comment by riversun** [comment]
fixed on ver. 1.4.2

**Comment by UnleashSpirit** [comment]
Hi,
Thanks for fixing this. Everything seems to works for now (no advanced tests)

But, and I'm sorry, now the lib goes up to 108Ko (from 23Ko in 1.4.1). It's may be a bit oversized and in contradiction with your goal to avoid the +80Ko of jQuery ?

**Comment by UnleashSpirit** [comment]
Damn 20Ko, lighter than all previous version !
Seems really great for my need now.
If ever I see some new thing during my tests i'll let you know.

Thanks !
